// All names
export const allNames = [
    "Dr. Connor Haugh & Dr. Andree Phillips",
    "Dr. Karen Ravanesi",
    "Dr. Robert & Mrs. Lisa Heaps",
    "Dr. Susan Jordan & Mr. Peter Jordan",
    "Miss Audrey Djiya & Mr. Pelkins Ajanoh",
    "Miss Caitlin Heaps",
    "Miss Catherine Rafter",
    "Miss Cecilia Rafter & Mr. Eddie Ma",
    "Miss Ellen Li & Mr. Henry Senger",
    "Miss Isabella Moson",
    "Miss Jessica Lee",
    "Miss Joanna Blieden",
    "Miss Margaret Heaps",
    "Miss Madeleine Rafter",
    "Miss Mary Rafter",
    "Mr. Andrew Davis",
    "Mr. Chase & Mrs. Annie Gilmore",
    "Mr. Connor Matthew Haugh",
    "Mr. Corey Schiff",
    "Mr. Cyrus Jamidar",
    "Mr. Dan & Ms. Maya Gorman",
    "Mr. Dylan Kavookjian",
    "Mr. Edward & Ms. Carolyn Wagner",
    "Mr. Garrett Watumull",
    "Mr. Harrison McCarthy & Ms. Amanda Brandeen",
    "Mr. Jack Heaps",
    "Mr. Jake Lee & Ms. Summer Atwood",
    "Mr. James & Mrs. Jane Goodrich",
    "Mr. Jeffery Simon & Ms. Samantha Simon",
    "Mr. John North & Ms. Kerry Quinn",
    "Mr. Joshua Ufberg & Ms. Robyn Sorid",
    "Mr. Justin & Ms. Leslie Cronin",
    "Mr. Karl & Ms. Katherine Spielmann",
    "Mr. Patrick Clancy",
    "Mr. Paul & Dr. Valerie Goodrich",
    "Mr. Peter & Mrs. Piper Griffith",
    "Mr. Phil & Mrs. Laura Stackpole",
    "Mr. Robbie Tanner & Ms. Dylan Krouse",
    "Mr. Saaheb Sidana & Ms. Margot Marchese",
    "Mr. Scott Chapin & Ms. Claire Collins",
    "Mr. Shaheen Siddiqui",
    "Mr. Thomas And Mrs. Jennifer Goodrich",
    "Mr. Will Konstant & Ms. Brittany Kaplan",
    "Mr. Zachary Drobner & Ms. Alexa Leopold",
    "Mrs. Ann Phillips",
    "Mrs. Christine & Mr. David Moson",
    "Mrs. Gail D'Alessio",
    "Mrs. Laurel & Mr. John Rafter",
    "Mrs. Lea & Mr. Age Hollander",
    "Mrs. Louise & Mr. Gareth Healy",
    "Mrs. Marina & Mr. Ivan Ritossa",
    "Mrs. Nicole & Mr. Connor Boehm",
    "Mrs. Susan & Mr. Mark Blieden",
    "Mrs. Susan Zimny & Mr. Shelly Sussman",
    "Mrs. Varney & Mr. Andrew Polydor",
    "Ms. Abby Baskin & Mr. Chris Rodriguez",
    "Ms. Abby Markowitz & Mr. Bailey White",
    "Ms. Amanda Fritz",
    "Ms. Carol & Mr. Thomas Catalano",
    "Ms. Caroline Vanacore",
    "Ms. Cathy & Mr. Doug Field",
    "Ms. Dani Gnibus & Mr. Rassan Walker Jr.",
    "Ms. Dorothy & Mr. Richard Peterson",
    "Ms. Elizabeth Markowitz & Mr. Benjamin Waller",
    "Ms. Emily Carrolo & Mr. Conor Harrity",
    "Ms. Grace Carney & Mr. Christopher Brown",
    "Ms. Henrietta Hung & Mr. Paul Perry",
    "Ms. Jehanna Axelrod & Mr. Daniel Drabinski",
    "Ms. Jennie & Mr. Simon Jeacock",
    "Ms. Jing Qu & Mr. Jason Nawrocki",
    "Ms. Katherine Lee & Mr. Christoph Ungerer",
    "Ms. Leslie & Mr. Bruce Meyers",
    "Ms. Lilybet MacRae",
    "Ms. Lucy Taylor & Mr. Chris Hugh -Jones",
    "Ms. Marie Harding & Mr. Jeffrey Curran",
    "Ms. Meaghan Haugh & Mr. Alexander Rafter",
    "Ms. Meredith Alaback & Mr. Connor Bliss",
    "Ms. Onolee Phillips & Mr. Kenneth Whicher",
    "Ms. Sabrina Siddiqui & Mr. Nathan Norville",
    "Ms. Shahauna Siddiqui & Mr. Peter Zyla",
    "Ms. Sophie Kerr & Mr. Hunter Johnstone",
  ];
  
  // Names with a rehearsal dinner count of 1 or 2
  export const rehearsalDinnerNames = [
    "Dr. Connor Haugh & Dr. Andree Phillips",
    "Miss Audrey Djiya & Mr. Pelkins Ajanoh",
    "Miss Cecilia Rafter & Mr. Eddie Ma",
    "Miss Catherine Rafter",
    "Miss Ellen Li & Mr. Henry Senger",
    "Miss Isabella Moson",
    "Miss Jessica Lee",
    "Miss Madeleine Rafter",
    "Mr. Connor Matthew Haugh",
    "Mr. Edward & Ms. Carolyn Wagner",
    "Mr. Patrick Clancy",
    "Mr. Peter & Mrs. Piper Griffith",
    "Mr. Robbie Tanner & Ms. Dylan Krouse",
    "Mr. Saaheb Sidana & Ms. Margot Marchese",
    "Mr. Zachary Drobner & Ms. Alexa Leopold",
    "Mrs. Ann Phillips",
    "Mrs. Christine & Mr. David Moson",
    "Mrs. Laurel & Mr. John Rafter",
    "Mrs. Louise & Mr. Gareth Healy",
    "Mrs. Nicole & Mr. Connor Boehm",
    "Ms. Grace Carney & Mr. Christopher Brown",
    "Ms. Jehanna Axelrod & Mr. Daniel Drabinski",
    "Ms. Lilybet MacRae",
    "Ms. Meaghan Haugh & Mr. Alexander Rafter",




  ];
  